//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_TASK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Product = new HashSet<Order_Product>();
        }
    
        public int Code { get; set; }
        public Nullable<int> ID { get; set; }
        public string Name { get; set; }
        public string Scale { get; set; }
        public string Ventor { get; set; }
        public string PdtDescription { get; set; }
        public Nullable<int> QtylnStock { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public string MSRP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Product> Order_Product { get; set; }
        public virtual Productline Productline { get; set; }
    }
}
